### PR TITLE
Use float versions of math.h functions when MR_USE_SINGLE_PREC_FLOAT …

### PR DESCRIPTION
**Pull request by AlaskanEmily**
…is defined

library/float.m:
library/math.m:
    As above.

### CODE REVIEW

**Comment by AlaskanEmily** [comment]
An example of the result of this change:
https://osdn.net/users/alaskanemily/pastebin/6218
It makes it so that (as far as I have been able to tell) no float/double conversions occur in the spf grades when using float or math module funcs or preds. In all the cases I checked it also (very slightly) reduces the resulting code size, but not by much.

**Comment by wangp** [comment]
Seems okay. Can you change it to use function-like macros instead, e.g.
```
#define ML_FLOAT_FLOOR(x)  floorf(x)
```

**Comment by AlaskanEmily** [comment]
OK, I made them function-style.

**Comment by wangp** [comment]
Thanks!

**Pull request merged**
