### PR TITLE
Fixes for TCL/Tk on macOS

### PR DESCRIPTION
**Pull request by poldy**
In particular, I installed an up-to-date version from Homebrew using "brew install tck-tk". I'm not sure how much longer Apple will bundle TCL/Tk with their OS.

### CODE REVIEW

**Comment by juliensf** [comment]
Until/If Apple remove their version (and it is still present as of Ventura) I think that should be the version we point at by default.  That said, I think we should document how to use a TCL/Tk installed using Homebrew instead.

**Comment by poldy** [comment]
What do you think of this?

**Comment by juliensf** [comment]
Yes, something like that.

**Comment by juliensf** [comment]
Pulled and merged -- thanks for that!

**Pull request closed without merging**
