### PR TITLE
Enable link-time code generation for MSVC.

### PR DESCRIPTION
**Pull request by AlaskanEmily**
This requires MSVC 2010 or greater. It reduces the size of hello-world programs by almost 5 MB (down to less than 500 kb). This is because by using only static libraries, the linker can't remove any unused symbols, and the entirety of the Mercury standard library is included in every program regardless of what modules and functions are actually used. The program I'm currently working on goes from 7.1 MB to 1.3 MB with this change.

I'm unsure if the availability of this option should be checked by the configure script. I don't really know if Mercury supports Visual C below 2010 (my attempts with some older Windows compilers, particularly Watcom, makes me doubt it). I also can't easily test that, Microsoft no longer hosts downloads of older toolchains for general use.

I also would wonder if adding an option like /O1 or /O2 to the OPT_FLAGS would be appropriate. I have been compiling and running with /O1 in the OPT_FLAGS (optimize for size, equivalent to -Os in GCC) for a while now with a variety of grades (none and hlc, with memprof, profdeep, decldebug, stseg, and spf) and have had no issues. I have not tested trailing in particular, but I find it unlikely it could break that.

### CODE REVIEW

**Comment by juliensf** [comment]
It would definitely be worth allowing the use of LTCG / LTO  and not just for MSVC -- the above reduction in executable size is quite impressive.   (I did try GCCs support for LTO out with Mercury a few years ago and it was distinctly underwhelming, maybe things have improved since then ...)  That said, I don't think we should irrevocably enable it for MSVC.  For the moment, I suggest adding a new configuration flag that enables LTCG for MSVC (e.g. something like --enable-msvc-ltcg).

Some other comments:

- Your change will only affect the Mercury compiler when it is invoked via mmake.  Other modes of invocation (e.g. mmc, mmc --make) do not use the mgnuc and ml scripts.  The relevant code for them lives in compiler/compile_target_code.m.

- Mercury requires at least MSVC 2013 since at least some support for C99 is now required.  (Notably the header file stdint.h is now required.)  The /LTCG option should always be available.

- I suggest using a separate variable in the ml script rather than repurposing NOLOGO.

-  For MSVC, the Mercury compiler should be generating plain old C; if MSVC's /O options break then it ain't Mercury that's broken!

**Comment by wangp** [comment]
I don't wish to pollute this thread, but in case it is relevant, here was my proposed patch a few years ago for ELF systems. I forgot if there was any reason I didn't commit it.
http://lists.mercurylang.org/archives/reviews/2014-August/017151.html

**Comment by AlaskanEmily** [comment]
Once any object files are LTCG, then the entire link operation is LTCG. That means that linking with the stdlib triggers it (during linking), even if you are not using mmake. So it "works out" for the hello world example.

That also explains why I was not seeing the the /LTCG for the linker being invoked, although the performance drop seems pretty slight (if noticeable at all). The "extra work" is the linker seeing it has a LTCG library/object file and then starting over, presumably that's happening almost immediately.

Using /O1 alone (no LTCG) reduces hello-world executable size to about 3 MB. It's using them together that really shrinks the minimum exe size.

I'll look at adding a configure switch for LTCG, as well as actually adding these options to how mmc calls cl.

I can make a separate PR that adds /O1.

**Comment by AlaskanEmily** [comment]
OK, I've update the request to actually pass -GL as cflags and -LTCG as linker flags when --enable-lto is set in configure, as well as passing this through the mgnu and ml scripts. I tested this with MSVC 2015. I also added a (mostly untested) use of -flto for gcc/clang, which I only tested to not totally fail on Linux using gcc 8.2. I know it will fail when using clang on OpenBSD for building parts of Mercury itself, since clang on OpenBSD (and I believe FreeBSD, although I haven't checked) can't handle going straight from .c to executable with -flto in one step for some reason. This happens with some of the utils (mfiltercc, as an example).

Let me know if there is anything I should change.

**Comment by juliensf** [comment]
Thanks for that! I've committed it along with a couple of other minor documentation additions.

**Pull request closed without merging**
