### PR TITLE
Add gmp_int data type based on GMP.

### PR DESCRIPTION
**Pull request by mgudemann**
This adds a gmp_int data type which corresponds to mpz_t of GMP (GNU
multi-precision library).

extras/gmp_int/gmp_int.m:
        Mercury module containing FFI bindings to GMP

extras/gmp_int/gmp_int_test.m:
        Test basic functions of gmp_int.m.

extras/gmp_int/README:
        Basic usage and compilation information.

extras/README:
        Announce gmp_int in extras folder.

### CODE REVIEW

**Comment by wangp** [comment]
I think we can merge this. Is there any more you wish to do on it? There are minor changes I would make but I can do that separately.

**Comment by mgudemann** [comment]
I saw that you changed the constants for mp_int in d627a93193ad4d9921ec6ad652e8a025a2bb7750 and did s.th. similar for gmp_int, too. If you're ok with this, I'll squash the commits, if not, I'll revert this commit.

For mp_int you wrote that the change is for intermodule optimization. Does not having these constants in this way prevent this optimization?

**Comment by wangp** [comment]
The foreign_decls will be copied to the module's .mh header file, which is #included into the .c files of other Mercury modules which import that module. The bodies of short foreign_procs will be copied into the module's .opt file. When intermodule optimisation is enabled, calls to those procedures may be replaced by the code from the .opt file.

So if another module contains a call

    X = gmp_int.zero,

instead of compiling that to a function call that returns the address of constant_zero, it can be replaced with an assignment to the address directly

    X = &GMP_INT_constant_zero;

hence the symbol needs to be visible outside of gmp_int.c

BTW, the second foreign_decl in your change should be foreign_code.

**Comment by mgudemann** [comment]
Ok, thanks for the explication.

I changed the foreign_decl to foreign_code for the declaration of the mpz_t variables, feel free to change if you referred to a different location.

All other commits are squashed.

**Comment by wangp** [comment]
Thanks, merged. I changed the semidet functions to semidet predicates here as well.

**Pull request closed without merging**
