### PR TITLE
Add mp_int data type based on libtommath.

### PR DESCRIPTION
**Pull request by mgudemann**
This adds a new datatype mp_int for faster multi-precision integer
computations. It is based on calling the libtommath library throught the
FFI and works only in the C grades using the Boehm garbage collector.

extras/mp_int/mp_int.m:
        Add FFI binding to libtommath with API similar to integer.m

extras/mp_int/mp_int_test.m:
        Test basic functionality of mp_int.m.

extras/mp_int/README.txt:
        Description of how-to download, compile and use the binding
        together with the library.

extras/README:
        Announce mp_int in extras folder.

### CODE REVIEW

**Comment by mgudemann** [comment]
I'll squash the commits into a single on, once the PR is reviewed.

**Comment by drbuckleyjr** [comment]
I am using mp_int for an implementation of a Miller-Rabin primality test and a Pollard rho algorithm for factoring large prime numbers. The bignum features of mp_int have made possible a speedup of at least a factor of 14, and in some instances much more. I hope that mp_int will become a permanent part of what Mercury has to offer.

**Comment by wangp** [comment]
Sorry for the delay. I haven't looked at it any further but there's no harm in merging it. Can you squash the changes?

**Comment by mgudemann** [comment]
no worries
The commits are squashed now.

**Comment by wangp** [comment]
Thanks, committed.

**Pull request closed without merging**
